package com.taskforge.job;
import com.taskforge.auth.User; import jakarta.persistence.*; import java.time.Instant;
@Entity @Table(name="jobs",indexes={@Index(name="ix_jobs_due",columnList="status,next_run_at"),@Index(name="ix_jobs_owner",columnList="owner_id,created_at"),@Index(name="ix_jobs_priority",columnList="priority")})
public class Job {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;
 @Version private long version;
 @ManyToOne(optional=false,fetch=FetchType.LAZY) private User owner;
 @Column(nullable=false,length=160) private String name; @Column(length=2000) private String description;
 @Column(nullable=false,length=80) private String type; @Column(nullable=false,columnDefinition="text") private String payload;
 @Enumerated(EnumType.STRING) @Column(name="schedule_type",nullable=false,length=24) private ScheduleType scheduleType; @Column(name="cron_expression",length=120) private String cronExpression; @Column(name="time_zone",nullable=false,length=80) private String timeZone="UTC"; @Column(name="next_run_at") private Instant nextRunAt;
 @Enumerated(EnumType.STRING) @Column(nullable=false,length=24) private JobPriority priority;
 @Enumerated(EnumType.STRING) @Column(nullable=false,length=24) private JobStatus status;
 private int maxRetries; private int timeoutSeconds; @Column(name="run_number",nullable=false) private int runNumber; private int attemptCount; @Column(name="cancellation_requested",nullable=false) private boolean cancellationRequested;
 @Column(name="created_at",nullable=false,updatable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
 protected Job() {}
 public Job(User owner,String name,String description,String type,String payload,ScheduleType scheduleType,String cronExpression,Instant nextRunAt,JobPriority priority,int maxRetries,int timeoutSeconds){this(owner,name,description,type,payload,scheduleType,cronExpression,"UTC",nextRunAt,priority,maxRetries,timeoutSeconds);}
 public Job(User owner,String name,String description,String type,String payload,ScheduleType scheduleType,String cronExpression,String timeZone,Instant nextRunAt,JobPriority priority,int maxRetries,int timeoutSeconds){this.owner=owner;this.name=name;this.description=description;this.type=type;this.payload=payload;this.scheduleType=scheduleType;this.cronExpression=cronExpression;this.timeZone=timeZone;this.nextRunAt=nextRunAt;this.priority=priority;this.maxRetries=maxRetries;this.timeoutSeconds=timeoutSeconds;this.status=nextRunAt==null?JobStatus.CREATED:JobStatus.SCHEDULED;this.createdAt=Instant.now();this.updatedAt=createdAt;}
 @PreUpdate void touch(){updatedAt=Instant.now();}
 public Long getId(){return id;} public User getOwner(){return owner;} public String getName(){return name;} public String getDescription(){return description;} public String getType(){return type;} public String getPayload(){return payload;} public ScheduleType getScheduleType(){return scheduleType;} public String getCronExpression(){return cronExpression;} public String getTimeZone(){return timeZone;} public Instant getNextRunAt(){return nextRunAt;} public JobPriority getPriority(){return priority;} public JobStatus getStatus(){return status;} public int getMaxRetries(){return maxRetries;} public int getTimeoutSeconds(){return timeoutSeconds;} public int getRunNumber(){return runNumber;} public int getAttemptCount(){return attemptCount;} public Instant getCreatedAt(){return createdAt;} public boolean isCancellationRequested(){return cancellationRequested;}
 public Instant nextCronRunAfter(Instant after){if(scheduleType!=ScheduleType.CRON)return null;return CronSupport.next(cronExpression,timeZone,after);}
 public void transition(JobStatus target){boolean ok=switch(status){case CREATED->target==JobStatus.SCHEDULED||target==JobStatus.QUEUED||target==JobStatus.CANCELLED;case SCHEDULED->target==JobStatus.QUEUED||target==JobStatus.CANCELLED;case QUEUED->target==JobStatus.RUNNING||target==JobStatus.CANCELLED;case RUNNING->target==JobStatus.SUCCESS||target==JobStatus.FAILED||target==JobStatus.RETRYING||target==JobStatus.TIMEOUT||target==JobStatus.CANCELLED||target==JobStatus.SCHEDULED;case RETRYING->target==JobStatus.QUEUED||target==JobStatus.CANCELLED;case TIMEOUT->target==JobStatus.RETRYING||target==JobStatus.FAILED||target==JobStatus.SCHEDULED;case SUCCESS,FAILED,CANCELLED->target==JobStatus.SCHEDULED;};if(!ok)throw new IllegalStateException("Invalid job transition: "+status+" -> "+target);status=target;updatedAt=Instant.now();}
 public void beginScheduledRun(){if(status!=JobStatus.SCHEDULED)throw new IllegalStateException("Only a scheduled job can begin a new run");runNumber++;attemptCount=0;}
 public int nextAttempt(){return ++attemptCount;} public void setNextRunAt(Instant at){nextRunAt=at;}
 public void requestCancellation(){if(status==JobStatus.RUNNING)cancellationRequested=true;else transition(JobStatus.CANCELLED);updatedAt=Instant.now();}
 public void updateDetails(String name,String description,String type,String payload,ScheduleType scheduleType,String cron,String zone,Instant nextRun,JobPriority priority,int retries,int timeout){if(status!=JobStatus.CREATED&&status!=JobStatus.SCHEDULED)throw new IllegalStateException("Only unstarted jobs can be edited");if(status==JobStatus.CREATED&&nextRun!=null)transition(JobStatus.SCHEDULED);this.name=name;this.description=description;this.type=type;this.payload=payload;this.scheduleType=scheduleType;this.cronExpression=cron;this.timeZone=zone;this.nextRunAt=nextRun;this.priority=priority;this.maxRetries=retries;this.timeoutSeconds=timeout;this.updatedAt=Instant.now();}
 public void triggerNow(){if(status==JobStatus.RUNNING||status==JobStatus.QUEUED||status==JobStatus.RETRYING)throw new IllegalStateException("Job is already active");if(status!=JobStatus.SCHEDULED)transition(JobStatus.SCHEDULED);nextRunAt=Instant.now();attemptCount=0;cancellationRequested=false;updatedAt=Instant.now();}
}
