package com.taskforge.job;
import org.springframework.data.jpa.repository.JpaRepository; import java.util.*;
public interface JobExecutionRepository extends JpaRepository<JobExecution,Long>{List<JobExecution> findByJobIdOrderByRunNumberDescAttemptNumberDesc(Long jobId);
 void deleteByJobId(Long jobId);
 @org.springframework.data.jpa.repository.Modifying @org.springframework.data.jpa.repository.Query(value="update job_executions set status='RUNNING', worker_id=:workerId, started_at=now(), lease_token=:token, lease_until=now() + (:leaseSeconds * interval '1 second') where id=:executionId and job_id=:jobId and run_number=:runNumber and status='QUEUED'",nativeQuery=true) int claimQueued(@org.springframework.data.repository.query.Param("executionId") Long executionId,@org.springframework.data.repository.query.Param("jobId") Long jobId,@org.springframework.data.repository.query.Param("runNumber") int runNumber,@org.springframework.data.repository.query.Param("workerId") String workerId,@org.springframework.data.repository.query.Param("token") String token,@org.springframework.data.repository.query.Param("leaseSeconds") int leaseSeconds);
 @org.springframework.data.jpa.repository.Lock(jakarta.persistence.LockModeType.PESSIMISTIC_WRITE) @org.springframework.data.jpa.repository.Query("select e from JobExecution e where e.id=:id") java.util.Optional<JobExecution> findByIdForUpdate(@org.springframework.data.repository.query.Param("id") Long id);
 @org.springframework.data.jpa.repository.Lock(jakarta.persistence.LockModeType.PESSIMISTIC_WRITE) @org.springframework.data.jpa.repository.Query("select e from JobExecution e where e.status='RUNNING' and e.leaseUntil <= :now") java.util.List<JobExecution> lockExpiredLeases(@org.springframework.data.repository.query.Param("now") java.time.Instant now,org.springframework.data.domain.Pageable pageable);
 @org.springframework.data.jpa.repository.Modifying @org.springframework.data.jpa.repository.Query(value="update job_executions e set lease_until=least(:leaseUntil, e.started_at + ((select j.timeout_seconds from jobs j where j.id=e.job_id) + 20) * interval '1 second') where e.worker_id=:workerId and e.status='RUNNING'",nativeQuery=true) int extendWorkerLeases(@org.springframework.data.repository.query.Param("workerId") String workerId,@org.springframework.data.repository.query.Param("leaseUntil") java.time.Instant leaseUntil);
}
