package com.taskforge.job;
import com.fasterxml.jackson.databind.ObjectMapper; import com.taskforge.auth.*; import com.taskforge.worker.WorkerRepository; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class JobService {
 public record CreateJob(@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=160) String name,@jakarta.validation.constraints.Size(max=2000) String description,@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=JobMessage.MAX_JOB_TYPE_LENGTH) String type,@jakarta.validation.constraints.NotNull Object payload,@jakarta.validation.constraints.NotNull ScheduleType scheduleType,@jakarta.validation.constraints.Size(max=120) String cronExpression,Instant runAt,@jakarta.validation.constraints.Size(max=80) String timeZone,JobPriority priority,@jakarta.validation.constraints.Min(0) @jakarta.validation.constraints.Max(JobMessage.MAX_RETRIES) Integer maxRetries,@jakarta.validation.constraints.Min(1) @jakarta.validation.constraints.Max(JobMessage.MAX_TIMEOUT_SECONDS) Integer timeoutSeconds){}
 private final JobRepository jobs;private final UserRepository users;private final ObjectMapper mapper;private final JobExecutionRepository executions;private final JobEventService events;private final com.taskforge.common.TaskForgeMetrics metrics;private final com.taskforge.common.AdminAuditService adminAudit;private final WorkerRepository workers;
 public JobService(JobRepository j,UserRepository u,ObjectMapper m,JobExecutionRepository e,JobEventService events,com.taskforge.common.TaskForgeMetrics metrics,com.taskforge.common.AdminAuditService adminAudit,WorkerRepository workers){jobs=j;users=u;mapper=m;executions=e;this.events=events;this.metrics=metrics;this.adminAudit=adminAudit;this.workers=workers;}
 @Transactional public Job create(String email,CreateJob r){String payload=serializePayload(r.payload());String zone=r.timeZone()==null||r.timeZone().isBlank()?"UTC":r.timeZone();String cron=r.scheduleType()==ScheduleType.CRON?CronSupport.normalize(r.cronExpression()):r.cronExpression();Instant now=Instant.now();Instant due=switch(r.scheduleType()){case IMMEDIATE->now;case ONE_TIME->r.runAt()==null?now:r.runAt();case CRON->CronSupport.next(cron,zone,now);};try{java.time.ZoneId.of(zone);}catch(java.time.DateTimeException e){throw new IllegalArgumentException("Invalid timeZone: "+zone,e);}Job j=jobs.save(new Job(users.findByEmail(email).orElseThrow(),r.name(),r.description(),r.type(),payload,r.scheduleType(),cron,zone,due,r.priority()==null?JobPriority.MEDIUM:r.priority(),r.maxRetries()==null?3:r.maxRetries(),r.timeoutSeconds()==null?300:r.timeoutSeconds()));events.record(j.getId(),null,j.getStatus(),null,"Job created");metrics.created();return j;}
 public Page<Job> list(String email,boolean admin,JobStatus status,Pageable p){if(admin)return status==null?jobs.findAll(p):jobs.findByStatus(status,p);User u=users.findByEmail(email).orElseThrow();return status==null?jobs.findByOwnerId(u.getId(),p):jobs.findByOwnerIdAndStatus(u.getId(),status,p);}
 @Transactional(readOnly=true) public Job get(Long id,String email,boolean admin){return authorize(jobs.findById(id).orElseThrow(()->new NoSuchElementException("Job not found")),email,admin);}
 private Job getForUpdate(Long id,String email,boolean admin){return authorize(jobs.findByIdForUpdate(id).orElseThrow(()->new NoSuchElementException("Job not found")),email,admin);}
 private Job authorize(Job j,String email,boolean admin){if(!admin&&!j.getOwner().getEmail().equals(email))throw new NoSuchElementException("Job not found");return j;}
 @Transactional public Job cancel(Long id,String email,boolean admin){Job j=getForUpdate(id,email,admin);j.requestCancellation();String detail=j.isCancellationRequested()?"Cancellation requested; worker will interrupt the handler":"Job cancelled before execution";events.record(j.getId(),null,j.getStatus(),null,detail);auditAdminMutation(admin,email,j,"JOB_CANCELLED",detail);return j;}
 @Transactional public Job update(Long id,String email,boolean admin,CreateJob r){Job j=getForUpdate(id,email,admin);String payload=serializePayload(r.payload());String zone=r.timeZone()==null||r.timeZone().isBlank()?"UTC":r.timeZone();try{java.time.ZoneId.of(zone);}catch(java.time.DateTimeException e){throw new IllegalArgumentException("Invalid timeZone: "+zone,e);}String cron=r.scheduleType()==ScheduleType.CRON?CronSupport.normalize(r.cronExpression()):r.cronExpression();Instant due=switch(r.scheduleType()){case IMMEDIATE->Instant.now();case ONE_TIME->r.runAt()==null?Instant.now():r.runAt();case CRON->CronSupport.next(cron,zone,Instant.now());};j.updateDetails(r.name(),r.description(),r.type(),payload,r.scheduleType(),cron,zone,due,r.priority()==null?JobPriority.MEDIUM:r.priority(),r.maxRetries()==null?3:r.maxRetries(),r.timeoutSeconds()==null?300:r.timeoutSeconds());events.record(j.getId(),null,j.getStatus(),null,"Job updated");auditAdminMutation(admin,email,j,"JOB_UPDATED","Job configuration updated");return j;}
 @Transactional public Job trigger(Long id,String email,boolean admin){Job j=getForUpdate(id,email,admin);if(workers.existsByCurrentJobIdAndStatus(id,com.taskforge.worker.WorkerStatus.BUSY))throw new IllegalStateException("A worker is still running this job's handler; it cannot be triggered again yet");j.triggerNow();events.record(j.getId(),null,j.getStatus(),null,"Manual trigger requested");auditAdminMutation(admin,email,j,"JOB_TRIGGERED","Manual execution requested");return j;}
 @Transactional public void delete(Long id,String email,boolean admin){Job existing=jobs.findById(id).orElseThrow(()->new NoSuchElementException("Job not found"));authorize(existing,email,admin);executions.lockAllByJobId(id);Job j=getForUpdate(id,email,admin);if(j.getStatus()==JobStatus.RUNNING||j.getStatus()==JobStatus.QUEUED||j.getStatus()==JobStatus.RETRYING||workers.existsByCurrentJobIdAndStatus(id,com.taskforge.worker.WorkerStatus.BUSY))throw new IllegalStateException("Active jobs or jobs with a still-running handler cannot be deleted");auditAdminMutation(admin,email,j,"JOB_DELETED","Job and execution history deleted");events.deleteByJobId(id);executions.deleteByJobId(id);jobs.delete(j);}
 private void auditAdminMutation(boolean admin,String email,Job job,String action,String detail){if(admin)adminAudit.record(email,"JOB",String.valueOf(job.getId()),action,detail);}
 private String serializePayload(Object payload){try{byte[] bytes=mapper.writeValueAsBytes(payload);if(bytes.length>JobMessage.MAX_PAYLOAD_BYTES)throw new IllegalArgumentException("Job payload must not exceed "+JobMessage.MAX_PAYLOAD_BYTES+" UTF-8 bytes");return new String(bytes,java.nio.charset.StandardCharsets.UTF_8);}catch(com.fasterxml.jackson.core.JsonProcessingException ex){throw new IllegalArgumentException("Payload must be valid JSON",ex);}}
 @Transactional(readOnly=true) public Page<JobExecution> history(Long id,String email,boolean admin,Pageable pageable){get(id,email,admin);return executions.findByJobIdOrderByRunNumberDescAttemptNumberDesc(id,pageable);}
}
