package com.taskforge.job;
import com.fasterxml.jackson.databind.ObjectMapper; import com.taskforge.auth.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class JobService {
 public record CreateJob(@jakarta.validation.constraints.NotBlank String name,String description,@jakarta.validation.constraints.NotBlank String type,@jakarta.validation.constraints.NotNull Object payload,@jakarta.validation.constraints.NotNull ScheduleType scheduleType,String cronExpression,Instant runAt,JobPriority priority,@jakarta.validation.constraints.Min(0) @jakarta.validation.constraints.Max(20) Integer maxRetries,@jakarta.validation.constraints.Min(1) @jakarta.validation.constraints.Max(86400) Integer timeoutSeconds){}
 private final JobRepository jobs;private final UserRepository users;private final ObjectMapper mapper;private final JobExecutionRepository executions;
 public JobService(JobRepository j,UserRepository u,ObjectMapper m,JobExecutionRepository e){jobs=j;users=u;mapper=m;executions=e;}
 @Transactional public Job create(String email,CreateJob r){try{if(r.scheduleType()==ScheduleType.CRON&&(r.cronExpression()==null||r.cronExpression().isBlank()))throw new IllegalArgumentException("cronExpression is required for CRON");Instant due=switch(r.scheduleType()){case IMMEDIATE->Instant.now();case ONE_TIME->r.runAt()==null?Instant.now():r.runAt();case CRON->Instant.now();};Job j=new Job(users.findByEmail(email).orElseThrow(),r.name(),r.description(),r.type(),mapper.writeValueAsString(r.payload()),r.scheduleType(),r.cronExpression(),due,r.priority()==null?JobPriority.MEDIUM:r.priority(),r.maxRetries()==null?3:r.maxRetries(),r.timeoutSeconds()==null?300:r.timeoutSeconds());return jobs.save(j);}catch(java.io.IOException ex){throw new IllegalArgumentException("Payload must be valid JSON",ex);}}
 public Page<Job> list(String email,boolean admin,Pageable p){if(admin)return jobs.findAll(p);User u=users.findByEmail(email).orElseThrow();return jobs.findByOwnerId(u.getId(),p);}
 public Job get(Long id,String email,boolean admin){Job j=jobs.findById(id).orElseThrow(()->new NoSuchElementException("Job not found"));if(!admin&&!j.getOwner().getEmail().equals(email))throw new NoSuchElementException("Job not found");return j;}
 @Transactional public Job cancel(Long id,String email,boolean admin){Job j=get(id,email,admin);j.transition(JobStatus.CANCELLED);return j;}
 public List<JobExecution> history(Long id,String email,boolean admin){get(id,email,admin);return executions.findByJobIdOrderByAttemptNumberDesc(id);}
}
