package com.taskforge.job;
import com.fasterxml.jackson.databind.ObjectMapper; import com.taskforge.auth.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class JobService {
 public record CreateJob(@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=160) String name,@jakarta.validation.constraints.Size(max=2000) String description,@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=80) String type,@jakarta.validation.constraints.NotNull Object payload,@jakarta.validation.constraints.NotNull ScheduleType scheduleType,@jakarta.validation.constraints.Size(max=120) String cronExpression,Instant runAt,@jakarta.validation.constraints.Size(max=80) String timeZone,JobPriority priority,@jakarta.validation.constraints.Min(0) @jakarta.validation.constraints.Max(20) Integer maxRetries,@jakarta.validation.constraints.Min(1) @jakarta.validation.constraints.Max(86400) Integer timeoutSeconds){}
 private final JobRepository jobs;private final UserRepository users;private final ObjectMapper mapper;private final JobExecutionRepository executions;private final JobEventService events;private final com.taskforge.common.TaskForgeMetrics metrics;
 public JobService(JobRepository j,UserRepository u,ObjectMapper m,JobExecutionRepository e,JobEventService events,com.taskforge.common.TaskForgeMetrics metrics){jobs=j;users=u;mapper=m;executions=e;this.events=events;this.metrics=metrics;}
 @Transactional public Job create(String email,CreateJob r){try{String zone=r.timeZone()==null||r.timeZone().isBlank()?"UTC":r.timeZone();String cron=r.scheduleType()==ScheduleType.CRON?CronSupport.normalize(r.cronExpression()):r.cronExpression();Instant now=Instant.now();Instant due=switch(r.scheduleType()){case IMMEDIATE->now;case ONE_TIME->r.runAt()==null?now:r.runAt();case CRON->CronSupport.next(cron,zone,now);};try{java.time.ZoneId.of(zone);}catch(java.time.DateTimeException e){throw new IllegalArgumentException("Invalid timeZone: "+zone,e);}Job j=jobs.save(new Job(users.findByEmail(email).orElseThrow(),r.name(),r.description(),r.type(),mapper.writeValueAsString(r.payload()),r.scheduleType(),cron,zone,due,r.priority()==null?JobPriority.MEDIUM:r.priority(),r.maxRetries()==null?3:r.maxRetries(),r.timeoutSeconds()==null?300:r.timeoutSeconds()));events.record(j.getId(),null,j.getStatus(),null,"Job created");metrics.created();return j;}catch(java.io.IOException ex){throw new IllegalArgumentException("Payload must be valid JSON",ex);}}
 public Page<Job> list(String email,boolean admin,JobStatus status,Pageable p){if(admin)return status==null?jobs.findAll(p):jobs.findByStatus(status,p);User u=users.findByEmail(email).orElseThrow();return status==null?jobs.findByOwnerId(u.getId(),p):jobs.findByOwnerIdAndStatus(u.getId(),status,p);}
 @Transactional(readOnly=true) public Job get(Long id,String email,boolean admin){return authorize(jobs.findById(id).orElseThrow(()->new NoSuchElementException("Job not found")),email,admin);}
 private Job getForUpdate(Long id,String email,boolean admin){return authorize(jobs.findByIdForUpdate(id).orElseThrow(()->new NoSuchElementException("Job not found")),email,admin);}
 private Job authorize(Job j,String email,boolean admin){if(!admin&&!j.getOwner().getEmail().equals(email))throw new NoSuchElementException("Job not found");return j;}
 @Transactional public Job cancel(Long id,String email,boolean admin){Job j=getForUpdate(id,email,admin);j.requestCancellation();events.record(j.getId(),null,j.getStatus(),null,j.isCancellationRequested()?"Cancellation requested; worker will interrupt the handler":"Job cancelled before execution");return j;}
 @Transactional public Job update(Long id,String email,boolean admin,CreateJob r){Job j=getForUpdate(id,email,admin);try{String zone=r.timeZone()==null||r.timeZone().isBlank()?"UTC":r.timeZone();try{java.time.ZoneId.of(zone);}catch(java.time.DateTimeException e){throw new IllegalArgumentException("Invalid timeZone: "+zone,e);}String cron=r.scheduleType()==ScheduleType.CRON?CronSupport.normalize(r.cronExpression()):r.cronExpression();Instant due=switch(r.scheduleType()){case IMMEDIATE->Instant.now();case ONE_TIME->r.runAt()==null?Instant.now():r.runAt();case CRON->CronSupport.next(cron,zone,Instant.now());};j.updateDetails(r.name(),r.description(),r.type(),mapper.writeValueAsString(r.payload()),r.scheduleType(),cron,zone,due,r.priority()==null?JobPriority.MEDIUM:r.priority(),r.maxRetries()==null?3:r.maxRetries(),r.timeoutSeconds()==null?300:r.timeoutSeconds());events.record(j.getId(),null,j.getStatus(),null,"Job updated");return j;}catch(java.io.IOException ex){throw new IllegalArgumentException("Payload must be valid JSON",ex);}}
 @Transactional public Job trigger(Long id,String email,boolean admin){Job j=getForUpdate(id,email,admin);j.triggerNow();events.record(j.getId(),null,j.getStatus(),null,"Manual trigger requested");return j;}
 @Transactional public void delete(Long id,String email,boolean admin){Job j=getForUpdate(id,email,admin);if(j.getStatus()==JobStatus.RUNNING||j.getStatus()==JobStatus.QUEUED||j.getStatus()==JobStatus.RETRYING)throw new IllegalStateException("Active jobs cannot be deleted");events.deleteByJobId(id);executions.deleteByJobId(id);jobs.delete(j);}
 @Transactional(readOnly=true) public List<JobExecution> history(Long id,String email,boolean admin){get(id,email,admin);return executions.findByJobIdOrderByRunNumberDescAttemptNumberDesc(id);}
}
