import http from 'k6/http';
import { check, sleep } from 'k6';
import { Rate, Trend } from 'k6/metrics';

const baseUrl = (__ENV.TASKFORGE_BASE_URL || 'http://localhost:8080').replace(/\/$/, '');
const email = __ENV.TASKFORGE_EMAIL;
const password = __ENV.TASKFORGE_PASSWORD;
const arrivalRate = Number(__ENV.JOBS_PER_MINUTE || '10');
const duration = __ENV.TEST_DURATION || '5m';
if (!Number.isInteger(arrivalRate) || arrivalRate < 1) {
  throw new Error('JOBS_PER_MINUTE must be a positive integer.');
}

export const jobCompletionRate = new Rate('taskforge_job_completion_rate');
export const jobCompletionSeconds = new Trend('taskforge_job_completion_seconds', true);
export const jobCreateMilliseconds = new Trend('taskforge_job_create_milliseconds', true);

export const options = {
  scenarios: {
    distributed_job_flow: {
      executor: 'constant-arrival-rate',
      rate: arrivalRate,
      timeUnit: '1m',
      duration,
      preAllocatedVUs: Math.max(5, arrivalRate),
      maxVUs: Math.max(25, arrivalRate * 3),
    },
  },
  thresholds: {
    http_req_failed: ['rate<0.01'],
    taskforge_job_completion_rate: ['rate>0.99'],
    taskforge_job_create_milliseconds: ['p(95)<1000'],
    taskforge_job_completion_seconds: ['p(95)<30'],
  },
};

export function setup() {
  if (!email || !password) {
    throw new Error('Set TASKFORGE_EMAIL and TASKFORGE_PASSWORD for an existing user.');
  }
  const response = http.post(`${baseUrl}/api/auth/login`, JSON.stringify({ email, password }), {
    headers: { 'Content-Type': 'application/json' },
  });
  const valid = check(response, {
    'login succeeds': (r) => r.status === 200 && Boolean(r.json('accessToken')),
  });
  if (!valid) throw new Error(`TaskForge login failed with HTTP ${response.status}`);
  return { token: response.json('accessToken') };
}

export default function (data) {
  const headers = {
    Authorization: `Bearer ${data.token}`,
    'Content-Type': 'application/json',
  };
  const createdAt = Date.now();
  const response = http.post(`${baseUrl}/api/jobs`, JSON.stringify({
    name: `Load report ${__VU}-${__ITER}-${createdAt}`,
    description: 'Generated by the TaskForge k6 load scenario',
    type: 'REPORT_GENERATION',
    payload: { reportType: 'LOAD_TEST' },
    scheduleType: 'IMMEDIATE',
    priority: 'MEDIUM',
    maxRetries: 0,
    timeoutSeconds: 30,
  }), { headers });
  jobCreateMilliseconds.add(response.timings.duration);

  const created = check(response, {
    'job accepted': (r) => (r.status === 200 || r.status === 201) && Boolean(r.json('id')),
  });
  if (!created) {
    jobCompletionRate.add(0);
    return;
  }

  const jobId = response.json('id');
  for (let poll = 0; poll < 30; poll++) {
    sleep(2);
    const statusResponse = http.get(`${baseUrl}/api/jobs/${jobId}`, { headers });
    if (!check(statusResponse, { 'job status readable': (r) => r.status === 200 })) {
      jobCompletionRate.add(0);
      return;
    }
    const status = statusResponse.json('status');
    if (status === 'SUCCESS') {
      jobCompletionSeconds.add((Date.now() - createdAt) / 1000);
      jobCompletionRate.add(1);
      return;
    }
    if (['FAILED', 'TIMEOUT', 'CANCELLED'].includes(status)) {
      jobCompletionRate.add(0);
      return;
    }
  }

  jobCompletionRate.add(0);
}
