package com.taskforge.common;
import jakarta.servlet.http.HttpServletRequest;import org.springframework.http.*;import org.springframework.web.bind.MethodArgumentNotValidException;import org.springframework.web.bind.annotation.*;import java.time.Instant;import java.util.*;
@RestControllerAdvice public class ApiExceptionHandler {
 public record ApiError(Instant timestamp,int status,String error,String message,String path,String requestId){}
 @ExceptionHandler(NoSuchElementException.class) ResponseEntity<ApiError> missing(NoSuchElementException e,HttpServletRequest r){return error(HttpStatus.NOT_FOUND,"NOT_FOUND",e.getMessage(),r);}
 @ExceptionHandler(IllegalArgumentException.class) ResponseEntity<ApiError> bad(IllegalArgumentException e,HttpServletRequest r){return error(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR",e.getMessage(),r);}
 @ExceptionHandler(IllegalStateException.class) ResponseEntity<ApiError> conflict(IllegalStateException e,HttpServletRequest r){return error(HttpStatus.CONFLICT,"INVALID_STATE",e.getMessage(),r);}
 @ExceptionHandler(org.springframework.dao.DataIntegrityViolationException.class) ResponseEntity<ApiError> integrity(org.springframework.dao.DataIntegrityViolationException e,HttpServletRequest r){return error(HttpStatus.CONFLICT,"CONFLICT","The operation conflicts with existing data",r);}
 @ExceptionHandler(org.springframework.http.converter.HttpMessageNotReadableException.class) ResponseEntity<ApiError> unreadable(org.springframework.http.converter.HttpMessageNotReadableException e,HttpServletRequest r){return error(HttpStatus.BAD_REQUEST,"INVALID_REQUEST","Request body is invalid",r);}
 @ExceptionHandler({org.springframework.web.method.annotation.MethodArgumentTypeMismatchException.class,org.springframework.web.bind.MissingServletRequestParameterException.class,jakarta.validation.ConstraintViolationException.class}) ResponseEntity<ApiError> invalidParameter(Exception e,HttpServletRequest r){return error(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","A request parameter is invalid or missing",r);}
 @ExceptionHandler(org.springframework.web.HttpRequestMethodNotSupportedException.class) ResponseEntity<ApiError> methodNotAllowed(org.springframework.web.HttpRequestMethodNotSupportedException e,HttpServletRequest r){return error(HttpStatus.METHOD_NOT_ALLOWED,"METHOD_NOT_ALLOWED","The HTTP method is not supported for this endpoint",r);}
 @ExceptionHandler(org.springframework.web.servlet.resource.NoResourceFoundException.class) ResponseEntity<ApiError> resourceMissing(org.springframework.web.servlet.resource.NoResourceFoundException e,HttpServletRequest r){return error(HttpStatus.NOT_FOUND,"NOT_FOUND","Resource not found",r);}
 @ExceptionHandler(org.springframework.security.core.AuthenticationException.class) ResponseEntity<ApiError> unauthenticated(org.springframework.security.core.AuthenticationException e,HttpServletRequest r){return error(HttpStatus.UNAUTHORIZED,"UNAUTHORIZED","Invalid credentials",r);}
 @ExceptionHandler(MethodArgumentNotValidException.class) ResponseEntity<ApiError> validation(MethodArgumentNotValidException e,HttpServletRequest r){return error(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR",e.getBindingResult().getFieldErrors().stream().map(x->x.getField()+": "+x.getDefaultMessage()).findFirst().orElse("Invalid request"),r);}
 @ExceptionHandler(Exception.class) ResponseEntity<ApiError> internal(Exception e,HttpServletRequest r){org.slf4j.LoggerFactory.getLogger(ApiExceptionHandler.class).error("Unhandled API error requestId={}",r.getHeader("X-Request-ID"),e);return error(HttpStatus.INTERNAL_SERVER_ERROR,"INTERNAL_ERROR","An internal error occurred",r);}
 private ResponseEntity<ApiError> error(HttpStatus s,String code,String message,HttpServletRequest r){String id=RequestIdFilter.idFor(r);if(id.isBlank())id=UUID.randomUUID().toString();return ResponseEntity.status(s).body(new ApiError(Instant.now(),s.value(),code,message,r.getRequestURI(),id));}
}
