package com.taskforge.common;
import com.fasterxml.jackson.databind.ObjectMapper;import com.taskforge.auth.JwtFilter; import org.springframework.boot.web.servlet.FilterRegistrationBean;import org.springframework.context.annotation.*; import org.springframework.http.MediaType;import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.web.SecurityFilterChain;import org.springframework.security.web.AuthenticationEntryPoint;import org.springframework.security.web.access.AccessDeniedHandler; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;import java.time.Instant;import java.util.Map;
@Configuration public class SecurityConfig {
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean FilterRegistrationBean<RequestIdFilter> requestIdFilterRegistration(RequestIdFilter filter){var registration=new FilterRegistrationBean<>(filter);registration.setEnabled(false);return registration;}
 @Bean FilterRegistrationBean<RateLimitFilter> rateLimitFilterRegistration(RateLimitFilter filter){var registration=new FilterRegistrationBean<>(filter);registration.setEnabled(false);return registration;}
 @Bean AuthenticationEntryPoint authenticationEntryPoint(ObjectMapper mapper){return (request,response,exception)->{response.setStatus(401);response.setContentType(MediaType.APPLICATION_JSON_VALUE);mapper.writeValue(response.getWriter(),Map.of("timestamp",Instant.now(),"status",401,"error","UNAUTHORIZED","message","Authentication required","path",request.getRequestURI(),"requestId",RequestIdFilter.idFor(request)));};}
 @Bean AccessDeniedHandler accessDeniedHandler(ObjectMapper mapper){return (request,response,exception)->{response.setStatus(403);response.setContentType(MediaType.APPLICATION_JSON_VALUE);mapper.writeValue(response.getWriter(),Map.of("timestamp",Instant.now(),"status",403,"error","FORBIDDEN","message","Insufficient permissions","path",request.getRequestURI(),"requestId",RequestIdFilter.idFor(request)));};}
 @Bean SecurityFilterChain filterChain(HttpSecurity http,JwtFilter jwt,RequestIdFilter requestId,RateLimitFilter rateLimit,AuthenticationEntryPoint authenticationEntryPoint,AccessDeniedHandler accessDeniedHandler)throws Exception{return http.csrf(c->c.disable()).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).exceptionHandling(e->e.authenticationEntryPoint(authenticationEntryPoint).accessDeniedHandler(accessDeniedHandler)).authorizeHttpRequests(a->a.requestMatchers("/","/index.html","/app.js","/styles.css","/favicon.ico","/api/auth/**","/actuator/health","/actuator/info","/swagger-ui/**","/swagger-ui.html","/v3/api-docs/**").permitAll().requestMatchers("/api/admin/**","/api/workers/**").hasRole("ADMIN").anyRequest().authenticated()).addFilterBefore(requestId,UsernamePasswordAuthenticationFilter.class).addFilterAfter(jwt,RequestIdFilter.class).addFilterAfter(rateLimit,JwtFilter.class).build();}
}
