package com.taskforge.common;
import com.fasterxml.jackson.databind.ObjectMapper;import com.taskforge.auth.JwtFilter; import org.springframework.boot.web.servlet.FilterRegistrationBean;import org.springframework.context.annotation.*; import org.springframework.http.MediaType;import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.web.SecurityFilterChain;import org.springframework.security.web.AuthenticationEntryPoint;import org.springframework.security.web.access.AccessDeniedHandler; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;import java.time.Instant;import java.util.Map;
@Configuration public class SecurityConfig {
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean org.springframework.web.cors.CorsConfigurationSource corsConfigurationSource(@org.springframework.beans.factory.annotation.Value("${taskforge.cors.allowed-origins:}") String allowedOrigins){
  var origins=java.util.Arrays.stream(allowedOrigins.split(",")).map(String::trim).filter(origin->!origin.isEmpty()).distinct().toList();
  if(origins.contains("*"))throw new IllegalArgumentException("CORS origins must be explicit; wildcard origins are not allowed");
  var cors=new org.springframework.web.cors.CorsConfiguration();cors.setAllowedOrigins(origins);cors.setAllowedMethods(java.util.List.of("GET","POST","PUT","DELETE","OPTIONS"));cors.setAllowedHeaders(java.util.List.of("Authorization","Content-Type","X-Request-ID"));cors.setExposedHeaders(java.util.List.of("X-Request-ID"));cors.setAllowCredentials(false);
  var source=new org.springframework.web.cors.UrlBasedCorsConfigurationSource();source.registerCorsConfiguration("/api/**",cors);return source;
 }
 @Bean FilterRegistrationBean<RequestIdFilter> requestIdFilterRegistration(RequestIdFilter filter){var registration=new FilterRegistrationBean<>(filter);registration.setEnabled(false);return registration;}
 @Bean FilterRegistrationBean<RateLimitFilter> rateLimitFilterRegistration(RateLimitFilter filter){var registration=new FilterRegistrationBean<>(filter);registration.setEnabled(false);return registration;}
 @Bean org.springframework.security.web.header.HeaderWriter dashboardPageSecurityHeaders(){return (request,response)->{String path=request.getRequestURI();if(path.equals("/")||path.equals("/index.html")){response.setHeader("Content-Security-Policy","default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; connect-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:");response.setHeader("Referrer-Policy","strict-origin-when-cross-origin");response.setHeader("Permissions-Policy","camera=(), microphone=(), geolocation=()");}};}
 @Bean AuthenticationEntryPoint authenticationEntryPoint(ObjectMapper mapper){return (request,response,exception)->{response.setStatus(401);response.setContentType(MediaType.APPLICATION_JSON_VALUE);mapper.writeValue(response.getWriter(),Map.of("timestamp",Instant.now(),"status",401,"error","UNAUTHORIZED","message","Authentication required","path",request.getRequestURI(),"requestId",RequestIdFilter.idFor(request)));};}
 @Bean AccessDeniedHandler accessDeniedHandler(ObjectMapper mapper){return (request,response,exception)->{response.setStatus(403);response.setContentType(MediaType.APPLICATION_JSON_VALUE);mapper.writeValue(response.getWriter(),Map.of("timestamp",Instant.now(),"status",403,"error","FORBIDDEN","message","Insufficient permissions","path",request.getRequestURI(),"requestId",RequestIdFilter.idFor(request)));};}
 @Bean SecurityFilterChain filterChain(HttpSecurity http,JwtFilter jwt,RequestIdFilter requestId,RateLimitFilter rateLimit,AuthenticationEntryPoint authenticationEntryPoint,AccessDeniedHandler accessDeniedHandler,org.springframework.security.web.header.HeaderWriter dashboardPageSecurityHeaders)throws Exception{return http.cors(org.springframework.security.config.Customizer.withDefaults()).csrf(c->c.disable()).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).exceptionHandling(e->e.authenticationEntryPoint(authenticationEntryPoint).accessDeniedHandler(accessDeniedHandler)).headers(headers->headers.addHeaderWriter(dashboardPageSecurityHeaders)).authorizeHttpRequests(a->a.requestMatchers("/","/index.html","/app.js","/styles.css","/favicon.ico","/api/auth/**","/actuator/health","/actuator/health/**","/actuator/info","/actuator/prometheus","/swagger-ui/**","/swagger-ui.html","/v3/api-docs/**").permitAll().requestMatchers("/api/admin/**","/api/workers/**").hasRole("ADMIN").anyRequest().authenticated()).addFilterBefore(requestId,UsernamePasswordAuthenticationFilter.class).addFilterAfter(jwt,RequestIdFilter.class).addFilterAfter(rateLimit,JwtFilter.class).build();}
}
